name: metadata_fetch
description: A dart library for extracting metadata on web pages such as OpenGraph, Meta, Twitter Cards, and Structured Data (Json-LD)
version: 0.4.0-nullsafety.0
homepage: https://github.com/jg-l/metadata_fetch

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0-nullsafety.0
  string_validator: ^0.2.0-nullsafety.0
  html: ^0.15.0-nullsafety.0

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.17
